<?xml version="1.0" encoding="utf-8"?><Database Name="PPOB" Class="ppobDataContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=MMTNOTE02\SQLSERVER2012;Initial Catalog=PPOB;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="PPOBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Member" Member="Members">
    <Type Name="Member">
      <Column Name="MemberId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Photo" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Nama" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="NoTelpon" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="KodeReverall" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TypeMember" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="TglBergabung" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PhotoKTP" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PhotoRekening" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PhotoKTPSelfie" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VoidRemark" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Token" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Flag" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ChangeBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ChangeDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Operator" Member="Operators">
    <Type Name="Operator">
      <Column Name="OperatorId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nama" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Flag" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ChangeBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ChangeDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PDAM" Member="PDAMs">
    <Type Name="PDAM">
      <Column Name="PDAMId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Deskripsi" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Flag" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ChangeBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ChangeDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Slider" Member="Sliders">
    <Type Name="Slider">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Photo" Type="System.Data.Linq.Binary" DbType="Binary(8000)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Judul" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DesSingkat" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DesPanjang" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Flag" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ChangeBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ChangeDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>